### ISSUE TITLE
Your are using Old APIs

### ISSUE THREAD

**Issue by imattaullah** [TheHasnatBD/uMe#1]
Your work is Excellent & amazing but issue is, your are using **old google service class path**. (InProjectGradle)

> classpath 'com.google.gms:google-services:3.1.1'

please build on 

>  classpath 'com.google.gms:google-services:4.2.0'

and use 16.0.5 Firebase api and 4.2.0 UIs

**Comment by TheHasnatBD** [comment]
Thank you so much for appreciating my work and  finding this issue. I'll fix this issue as soon as possible.

**Comment by attaullahpro** [comment]
> 
> 
> Thank you so much for appreciating my work and finding this issue. I'll fix this issue as soon as possible.

**Devices having having API <24 then** 
issue: image present in **_drawable-24_** folder then it was not available on **API<24** devices.
fixed:  https://stackoverflow.com/a/50782550/2387564

**After updating to new API your will need these changes**
issue: **_firebaserecycleradapter()_** cannot be applied to FirebaseRecyclerAdapter
fixed: https://stackoverflow.com/a/47092932/2387564



issue: Cannot resolve **_taskSnapshot.getDownloadUrl()_** in android firebase
fixed: https://stackoverflow.com/a/52152484/2387564

**Comment by imattaullah** [comment]
> 
> 
> Thank you so much for appreciating my work and finding this issue. I'll fix this issue as soon as possible.

**Devices having having API <24 then** 
issue: image present in **_drawable-24_** folder then it was not available on **API<24** devices.
fixed:  https://stackoverflow.com/a/50782550/2387564

**After updating to Firebase new APIs your will need these changes**
issue: **_firebaserecycleradapter()_** cannot be applied to FirebaseRecyclerAdapter
fixed: https://stackoverflow.com/a/47092932/2387564

issue: Cannot resolve **_taskSnapshot.getDownloadUrl()_** in android firebase
fixed: https://stackoverflow.com/a/52152484/2387564

for better performance use Glide instead of Picasso
    

```
//    implementation 'com.squareup.picasso:picasso:2.71828'
//    implementation 'com.squareup.okhttp3:okhttp:3.11.0'
      implementation 'com.github.bumptech.glide:glide:4.8.0'
      annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
```
Replace Picasso
```
                Glide.with(holder.senderImageMsg.getContext())
                         .load(message.getMessage()) 
                         .apply(new RequestOptions().centerCrop()
                                 .placeholder(R.drawable.default_profile_image)
                                 .diskCacheStrategy(DiskCacheStrategy.DATA))
                         .into(holder.user_profile_image);
 
               /*  Picasso.get()
                        .load(message.getMessage())
                        .networkPolicy(NetworkPolicy.OFFLINE) // for Offline
                        .placeholder(R.drawable.default_profile_image)
                        .into(holder.senderImageMsg); */
```

**Comment by TheHasnatBD** [comment]
Thanks a lot for your contribution.

**Comment by TheHasnatBD** [comment]
Your finding issues have been fixed on [Nov 19, 2018](https://github.com/TheHasnatBD/uMe/commit/8decf93655bb847dee22d81c7ceb266ffb452025) & [Nov 22, 2018](https://github.com/TheHasnatBD/uMe/commit/7d72843f7081f9273535b8f8c65b76a7cc987d93) commits.  Thanks for your cooperation.
