### ISSUE TITLE
notification index.js  is missing

### ISSUE THREAD

**Issue by Erraoudy** [TheHasnatBD/uMe#3]
notification index.js  is missing

**Comment by mfarchana** [comment]
Please fix it

**Comment by yash21212** [comment]
have you fix it

**Comment by Erraoudy** [comment]
yes, check attached file 
[index.js.zip](https://github.com/TheHasnatBD/uMe/files/3835280/index.js.zip)

**Comment by yash21212** [comment]
Sir when image is send it will be displayed but
when many message is send when I scroll up few message will b disappeared
and some times image will not be visible can you please help me

**Comment by yash21212** [comment]
> yes, check attached file
> [index.js.zip](https://github.com/TheHasnatBD/uMe/files/3835280/index.js.zip)

Where attach it please help me

**Comment by yash21212** [comment]
> yes, check attached file
> [index.js.zip](https://github.com/TheHasnatBD/uMe/files/3835280/index.js.zip)

Sir when image is send it will be displayed but
when many message is send when I scroll up few message will b disappeared
and some times image will not be visible can you please help me its compulsory

**Comment by VN0** [comment]
Thanks
