### ISSUE TITLE
google-services.json file is missing

### ISSUE THREAD

**Issue by DevenderPabbathi** [TheHasnatBD/uMe#4]
while running application on android studio it's showing warning like google-serives.json is missing.
could you please upload it once

**Comment by TheHasnatBD** [comment]
Please create your own **google-services.json** file using your app package name & your personal Firebase account.

To download a **google-service.json** for an Android app:
- Sign in to Firebase and open your project.
- Click and select **Project settings**.
- In the Your apps card, select the package name of the app you need a config file for from the list.
- Click **google-services.json**.

After downloading file, paste the **google-services.json** file to your project’s app folder.

Thank you.

**Comment by DevenderPabbathi** [comment]
im asking about your project .json file
in firebase im not able to download that file

**Comment by DevenderPabbathi** [comment]
will you please mail it to devenderpabbathi403@gmail.com
